noinst_PROGRAMS =
noinst_PROGRAMS += test-mongo-bson
noinst_PROGRAMS += test-mongo-client

TEST_PROGS += test-mongo-bson
TEST_PROGS += test-mongo-client

test_mongo_client_SOURCES = $(top_srcdir)/tests/test-mongo-client.c
test_mongo_client_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_client_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la

test_mongo_bson_SOURCES = $(top_srcdir)/tests/test-mongo-bson.c
test_mongo_bson_CPPFLAGS = $(GIO_CFLAGS) $(GOBJECT_CFLAGS)
test_mongo_bson_LDADD = $(GIO_LIBS) $(GOBJECT_LIBS) $(top_builddir)/libmongo-glib-1.0.la
